function genrcvp(file,dirs)
%-------------------------------------------------------------------------------
% [system] : GpsTools
% [module] : generate station approx position table
% [func]   : generate station approx position table
% [argin]  : file = output file
% [argout] :
% [note]   :
% [version]: $Revision: 1 $ $Date: 06/07/08 8:57 $
% [history]: 04/10/28  0.1  new
%-------------------------------------------------------------------------------
if nargin<2, dirs='e:\gps\pos'; end
rcvs=prm_gpsrcvs;
rcvs=rcvs(:,1);
poss=shiftdim(readpos(caltomjd([2004,10,1]),0,rcvs,dirs),1);
f=fopen(file,'wt'); if f<0, return, end
fprintf(f,'%% generated by %s\n',mfilename);
fprintf(f,'prm={\n');
fprintf(f,'%% station  lon(deg)    lat(deg)   height(m)\n');
for n=1:size(poss,2)
    rcv=['''',rcvs{n},''','];
    gpos=eceftogeod(poss(:,n));
    fprintf(f,'%-9s%11.4f,%11.4f,%11.4f\n',rcv,gpos([2,1,3]));
end
fprintf(f,'};\n');
fclose(f);
