function geneph(td,varargin)
%-------------------------------------------------------------------------------
% [system] : GpsTools
% [module] : satellite ephemerides generator
% [func]   : read precise ephemerides and interporate positions and velocities
% [argin]  : td = start date (mjd-gpst)
%           (opts) = options
%                'span',span    = time span (days)         (default:1)
%                'sats',sats    = satellites list          (default:all gps)
%                'ephsrc',src   = precise ephemeris source (default:'igs')
%                'epherp',src   = erp source               (default:'bulb')
%                'dirs',dirs    = input directories
%                           dirs.eph = ephemeris
%                           dirs.erp = earth rotation parameters
%                'outdir',outdir= output directory         (default:current)
%                'tint',tint    = time interval (sec)      (default:30)
%                'tunit',tunit  = output unit time (hr)    (default:24)
% [argout] : none
% [note]   : output file
%            ephs_{sat}_YYYYMMDDHH.mat : ephemeris data
%                epoch = start epoch [year,month,day,hour,min,sec] (gpst)
%                time  = time vector relative to epoch (sec)
%                sat   = satellite
%                data  = satellite position/velocity [pos1,vel1;...] (m,m/sec)
%                sig   = satellite pos/vel std. deviation [pos1,vel1;...] (m,m/sec)
%                comment = comment
% [version]: $Revision: 8 $ $Date: 06/07/20 11:20 $
%            Copyright(c) 2004-2006 by T.Takasu, all rights reserved
% [history]: 04/11/16  0.1  new
%            04/12/11  0.2  support gui interface
%            05/02/28  0.3  use interpeph.m
%            05/05/20  0.4  add sig in output file
%                           add option epherp, delete option utc_tai
%-------------------------------------------------------------------------------
ver=gpstools('version');
if nargin<1, error('argin error'), end
sats={}; for n=1:31, sats={sats{:},sprintf('GPS%02d',n)}; end
span=1; ephsrc='igs'; erpsrc='bulb'; dirs.eph=''; dirs.erp=''; outdir='';
tint=30; tunit=24; n=1;
while n<=length(varargin)
    switch varargin{n}
    case 'span',  span  =varargin{n+1}; n=n+2;
    case 'sats',  sats  =varargin{n+1}; if ischar(sats), sats={sats}; end, n=n+2;
    case 'ephsrc',ephsrc=varargin{n+1}; n=n+2;
    case 'erpsrc',erpsrc=varargin{n+1}; n=n+2;
    case 'dirs',  dirs  =varargin{n+1}; n=n+2;
    case 'outdir',outdir=varargin{n+1}; n=n+2;
    case 'tint',  tint  =varargin{n+1}; n=n+2;
    case 'tunit', tunit =varargin{n+1}; n=n+2;
    otherwise, error('argin error'), end
end
tt=td-floor(td);
ts=floor(tt*24/tunit)*tunit*3600;
te=floor((tt+span)*24/tunit)*tunit*3600;
for t=ts:tunit*3600:te-tint
    abort=GenEphData(floor(td),t:tint:t+tunit*3600,sats,dirs,outdir,ephsrc,...
                     erpsrc,ver);
    if abort, break, end
end

% generate ephemeris data ------------------------------------------------------
function abort=GenEphData(td,time,sats,dirs,outdir,ephsrc,erpsrc,ver)
abort=0;
for n=1:length(sats)
    msg=sprintf('%s : %04d/%02d/%02d %02d:%02d:%02.0f sat=%s',mfilename,...
                mjdtocal(td,time(1)),sats{n});
    abort=gmsg((n-1)/length(sats),msg); if abort, break, end
    
    t=round(time(1)/900:time(end)/900)*900;;
    [pos,sig]=readeph(td,t,sats{n},dirs.eph,ephsrc);
    if any(~isnan(pos(:,1)))
        eph=interpeph(td,t,pos(:,1:3),sats{n},time,erpsrc,dirs);
        sig=interp1(t,sig(:,1:3),time); sig=[sig,zeros(size(sig))];
        SaveEphData(td,time(1:end-1),sats{n},eph(1:end-1,:),sig(1:end-1,:),...
                    outdir,ephsrc,erpsrc,ver);
    end
end

% save ephemeris data ----------------------------------------------------------
function SaveEphData(td,time,sat,data,sig,dirs,ephsrc,erpsrc,ver)
epoch=mjdtocal(td,time(1));
[td,ts]=caltomjd(epoch);
time=time(:)+(ts-time(1));
comment=sprintf('generated by %s ver.%s; eph source=%s; erp source=%s',...
                mfilename,ver,ephsrc,erpsrc);
file=sprintf('ephs_%s_%04d%02d%02d%02d.mat',sat,epoch(1:4));
file=gfilepath(dirs,file,epoch,sat,1);
gmsg([],['save : ',file]);
save(file,'epoch','time','sat','data','sig','comment')
