function genrcvp(file,dirs,dv)
%-------------------------------------------------------------------------------
% [system] : GpsTools
% [module] : generate station approx position table
% [func]   : generate station approx position table
% [argin]  : file = output file
% [argout] :
% [note]   :
% [version]: $Revision: 16 $ $Date: 2008-12-12 15:49:30 +0900 (金, 12 12 2008) $
% [history]: 04/10/28  0.1  new
%-------------------------------------------------------------------------------
if nargin<1, file='rcvs_poss.txt'; end
if nargin<2, dirs='k:\gps\pos'; end
if nargin<3, dv=[2007,1,1];; end
rcvs=prm_gpsrcvs;
rcvs=rcvs(:,1);
poss=shiftdim(readpos(caltomjd(dv),0,rcvs,dirs),1);
f=fopen(file,'wt'); if f<0, return, end
fprintf(f,'%% generated by %s\n',mfilename);
fprintf(f,'prm={\n');
fprintf(f,'%% station  lon(deg)    lat(deg)   height(m)\n');
for n=1:size(poss,2)
    rcv=['''',rcvs{n},''','];
    gpos=eceftogeod(poss(:,n));
    fprintf(f,'%-9s%11.4f,%11.4f,%11.4f\n',rcv,gpos([2,1,3]));
end
fprintf(f,'};\n');
fclose(f);
